---
# Source: cost-analyzer/templates/cost-analyzer-checks-template.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cost-analyzer-checks
  labels:
    
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.48.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cost-analyzer-checks
            image: ajaytripathy/kubecost-checks:prod-1.48.0
            imagePullPolicy: Always
            args:
            - node
            - ./node/cron.js
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 20m
                memory: 100Mi
            env:
            - name: COST_ANALYZER_SERVER_ENDPOINT
              value: RELEASE-NAME-cost-analyzer.default:9001
            - name: COST_ANALYZER_MODEL_ENDPOINT
              value: RELEASE-NAME-cost-analyzer.default:9003
            - name: PROMETHEUS_ALERTMANAGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: RELEASE-NAME-cost-analyzer
                  key: prometheus-alertmanager-endpoint
          restartPolicy: OnFailure
