apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-dev
  namespace: dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"
    requests.storage: "10Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-staging
  namespace: staging
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    requests.storage: "25Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-production
  namespace: production
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 16Gi
    persistentvolumeclaims: "20"
    requests.storage: "50Gi"