apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksrbac-dev-admin
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "ae7ebb94-4041-4ee8-a156-7a3b0e161556"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksrbac-dev-reader
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "b6f0caea-13aa-4101-8eb8-c9fa1ed91f4f"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksrbac-staging-admin
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "ae7ebb94-4041-4ee8-a156-7a3b0e161556"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksrbac-production-reader
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "b6f0caea-13aa-4101-8eb8-c9fa1ed91f4f"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksrbac-production-admin
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "ae7ebb94-4041-4ee8-a156-7a3b0e161556"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aksrbac-production-reader
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "b6f0caea-13aa-4101-8eb8-c9fa1ed91f4f"
